// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Hash } from './hash.js';


export class BlockHash {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockHash {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockHash(bb:flatbuffers.ByteBuffer, obj?:BlockHash):BlockHash {
  return (obj || new BlockHash()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockHash(bb:flatbuffers.ByteBuffer, obj?:BlockHash):BlockHash {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockHash()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

hash(obj?:Hash):Hash|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Hash()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startBlockHash(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addHash(builder:flatbuffers.Builder, hashOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, hashOffset, 0);
}

static endBlockHash(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBlockHash(builder:flatbuffers.Builder, hashOffset:flatbuffers.Offset):flatbuffers.Offset {
  BlockHash.startBlockHash(builder);
  BlockHash.addHash(builder, hashOffset);
  return BlockHash.endBlockHash(builder);
}
}
