// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BlockHash } from '../nng-interface/block-hash.js';


export class ChainStateFlushed {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChainStateFlushed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChainStateFlushed(bb:flatbuffers.ByteBuffer, obj?:ChainStateFlushed):ChainStateFlushed {
  return (obj || new ChainStateFlushed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChainStateFlushed(bb:flatbuffers.ByteBuffer, obj?:ChainStateFlushed):ChainStateFlushed {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChainStateFlushed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

blockHash(obj?:BlockHash):BlockHash|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new BlockHash()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startChainStateFlushed(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBlockHash(builder:flatbuffers.Builder, blockHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, blockHashOffset, 0);
}

static endChainStateFlushed(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChainStateFlushed(builder:flatbuffers.Builder, blockHashOffset:flatbuffers.Offset):flatbuffers.Offset {
  ChainStateFlushed.startChainStateFlushed(builder);
  ChainStateFlushed.addBlockHash(builder, blockHashOffset);
  return ChainStateFlushed.endChainStateFlushed(builder);
}
}
