// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetBlockRangeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetBlockRangeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetBlockRangeRequest(bb:flatbuffers.ByteBuffer, obj?:GetBlockRangeRequest):GetBlockRangeRequest {
  return (obj || new GetBlockRangeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetBlockRangeRequest(bb:flatbuffers.ByteBuffer, obj?:GetBlockRangeRequest):GetBlockRangeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetBlockRangeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

startHeight():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

numBlocks():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startGetBlockRangeRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addStartHeight(builder:flatbuffers.Builder, startHeight:number) {
  builder.addFieldInt32(0, startHeight, 0);
}

static addNumBlocks(builder:flatbuffers.Builder, numBlocks:number) {
  builder.addFieldInt32(1, numBlocks, 0);
}

static endGetBlockRangeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetBlockRangeRequest(builder:flatbuffers.Builder, startHeight:number, numBlocks:number):flatbuffers.Offset {
  GetBlockRangeRequest.startGetBlockRangeRequest(builder);
  GetBlockRangeRequest.addStartHeight(builder, startHeight);
  GetBlockRangeRequest.addNumBlocks(builder, numBlocks);
  return GetBlockRangeRequest.endGetBlockRangeRequest(builder);
}
}
