// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Block } from '../nng-interface/block.js';


export class GetBlockRangeResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetBlockRangeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetBlockRangeResponse(bb:flatbuffers.ByteBuffer, obj?:GetBlockRangeResponse):GetBlockRangeResponse {
  return (obj || new GetBlockRangeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetBlockRangeResponse(bb:flatbuffers.ByteBuffer, obj?:GetBlockRangeResponse):GetBlockRangeResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetBlockRangeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

blocks(index: number, obj?:Block):Block|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Block()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

blocksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetBlockRangeResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBlocks(builder:flatbuffers.Builder, blocksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, blocksOffset, 0);
}

static createBlocksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBlocksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetBlockRangeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetBlockRangeResponse(builder:flatbuffers.Builder, blocksOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetBlockRangeResponse.startGetBlockRangeResponse(builder);
  GetBlockRangeResponse.addBlocks(builder, blocksOffset);
  return GetBlockRangeResponse.endGetBlockRangeResponse(builder);
}
}
