// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MempoolTx } from '../nng-interface/mempool-tx.js';


export class GetMempoolResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetMempoolResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetMempoolResponse(bb:flatbuffers.ByteBuffer, obj?:GetMempoolResponse):GetMempoolResponse {
  return (obj || new GetMempoolResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetMempoolResponse(bb:flatbuffers.ByteBuffer, obj?:GetMempoolResponse):GetMempoolResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetMempoolResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

txs(index: number, obj?:MempoolTx):MempoolTx|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MempoolTx()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

txsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGetMempoolResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTxs(builder:flatbuffers.Builder, txsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, txsOffset, 0);
}

static createTxsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTxsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGetMempoolResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetMempoolResponse(builder:flatbuffers.Builder, txsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetMempoolResponse.startGetMempoolResponse(builder);
  GetMempoolResponse.addTxs(builder, txsOffset);
  return GetMempoolResponse.endGetMempoolResponse(builder);
}
}
