// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TxId } from '../nng-interface/tx-id.js';


export class TransactionRemovedFromMempool {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TransactionRemovedFromMempool {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTransactionRemovedFromMempool(bb:flatbuffers.ByteBuffer, obj?:TransactionRemovedFromMempool):TransactionRemovedFromMempool {
  return (obj || new TransactionRemovedFromMempool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTransactionRemovedFromMempool(bb:flatbuffers.ByteBuffer, obj?:TransactionRemovedFromMempool):TransactionRemovedFromMempool {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TransactionRemovedFromMempool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

txid(obj?:TxId):TxId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TxId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startTransactionRemovedFromMempool(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTxid(builder:flatbuffers.Builder, txidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, txidOffset, 0);
}

static endTransactionRemovedFromMempool(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTransactionRemovedFromMempool(builder:flatbuffers.Builder, txidOffset:flatbuffers.Offset):flatbuffers.Offset {
  TransactionRemovedFromMempool.startTransactionRemovedFromMempool(builder);
  TransactionRemovedFromMempool.addTxid(builder, txidOffset);
  return TransactionRemovedFromMempool.endTransactionRemovedFromMempool(builder);
}
}
