// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Block } from '../nng-interface/block.js';
import { TxId } from '../nng-interface/tx-id.js';


export class BlockConnected {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockConnected {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockConnected(bb:flatbuffers.ByteBuffer, obj?:BlockConnected):BlockConnected {
  return (obj || new BlockConnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockConnected(bb:flatbuffers.ByteBuffer, obj?:BlockConnected):BlockConnected {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockConnected()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

block(obj?:Block):Block|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Block()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

txsConflicted(index: number, obj?:TxId):TxId|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TxId()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

txsConflictedLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startBlockConnected(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBlock(builder:flatbuffers.Builder, blockOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, blockOffset, 0);
}

static addTxsConflicted(builder:flatbuffers.Builder, txsConflictedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, txsConflictedOffset, 0);
}

static createTxsConflictedVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTxsConflictedVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endBlockConnected(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBlockConnected(builder:flatbuffers.Builder, blockOffset:flatbuffers.Offset, txsConflictedOffset:flatbuffers.Offset):flatbuffers.Offset {
  BlockConnected.startBlockConnected(builder);
  BlockConnected.addBlock(builder, blockOffset);
  BlockConnected.addTxsConflicted(builder, txsConflictedOffset);
  return BlockConnected.endBlockConnected(builder);
}
}
