// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class BlockHeight {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BlockHeight {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBlockHeight(bb:flatbuffers.ByteBuffer, obj?:BlockHeight):BlockHeight {
  return (obj || new BlockHeight()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBlockHeight(bb:flatbuffers.ByteBuffer, obj?:BlockHeight):BlockHeight {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BlockHeight()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startBlockHeight(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(0, height, 0);
}

static endBlockHeight(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBlockHeight(builder:flatbuffers.Builder, height:number):flatbuffers.Offset {
  BlockHeight.startBlockHeight(builder);
  BlockHeight.addHeight(builder, height);
  return BlockHeight.endBlockHeight(builder);
}
}
