// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TxOut {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TxOut {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTxOut(bb:flatbuffers.ByteBuffer, obj?:TxOut):TxOut {
  return (obj || new TxOut()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTxOut(bb:flatbuffers.ByteBuffer, obj?:TxOut):TxOut {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TxOut()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

amount():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

script(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

scriptLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

scriptArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startTxOut(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAmount(builder:flatbuffers.Builder, amount:bigint) {
  builder.addFieldInt64(0, amount, BigInt('0'));
}

static addScript(builder:flatbuffers.Builder, scriptOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, scriptOffset, 0);
}

static createScriptVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startScriptVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endTxOut(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTxOut(builder:flatbuffers.Builder, amount:bigint, scriptOffset:flatbuffers.Offset):flatbuffers.Offset {
  TxOut.startTxOut(builder);
  TxOut.addAmount(builder, amount);
  TxOut.addScript(builder, scriptOffset);
  return TxOut.endTxOut(builder);
}
}
